try a different way

diff --git a/actions/send_email_workflow_status/action.yml b/actions/send_email_workflow_status/action.yml
--- a/actions/send_email_workflow_status/action.yml
+++ b/actions/send_email_workflow_status/action.yml
@@ -63,15 +63,10 @@ runs:
         # Prepare email
 
         # Status uppercase : SUCCESS / FAILURE (other value is unexpected)
-        #status="${{ env.WORKFLOW_CONCLUSION }}"
-        repo="${{ github.repository }}"
-        run_id="${{ github.run_id }}"
-        status=$(curl -L \
-        -H "Accept: application/vnd.github+json" \
-        -H "Authorization: Bearer ${{ inputs.ciToken }}" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id}} | jq -r '.conclusion')
-        status="${status^^}"
+        status="SUCCESS"
+        if ! grep -q "BUILD SUCCESS" ${{ inputs.mvn-output-file }}; then
+          echo "FAILED"
+        fi
         echo "Status is: $status"
 
         
