Debug maven version

diff --git a/actions/maven_get_project_version/action.yml b/actions/maven_get_project_version/action.yml
--- a/actions/maven_get_project_version/action.yml
+++ b/actions/maven_get_project_version/action.yml
@@ -21,6 +21,11 @@ runs:
       id: maven_get_project_version
       run: |
         echo "Maven get project version"
+
+        echo "Maven version:"
+        which mvn || echo "mvn command not found !"
+        mvn --version
+
         PROJECT_VERSION=$(mvn -B -q -f "${{ inputs.pom-xml-file }}" -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
         echo "PROJECT_VERSION [${PROJECT_VERSION}]"
         echo "::set-output name=PROJECT_VERSION::${PROJECT_VERSION}"
